export default {
  Order: [
    "ID",
    "Name",
    "Billing address matches shipping address",
    "Can mark as paid",
    "Can notify customer",
    "Cancelled at",
    "Capturable",
    "Cart discount",
    "Client ip",
    "Closed",
    "Closed at",
    "Confirmed",
    "Created at",
    "Customer locale",
    "Discount code",
    "Displayed fulfillment status",
    "Email",
    "Fulfillable",
    "Fully paid",
    "Has timeline comment",
    "Merchant editable",
    "Net payment",
    "Note",
    "Payment gateways",
    "Phone",
    "Processed at",
    "Refundable",
    "Requires shipping",
    "Restockable",
    "Subtotal quantity",
    "Subtotal price",
    "Tags",
    "Taxes included",
    "Is test",
    "Total capturable",
    "Total discounts",
    "Total price",
    "Total received",
    "Total refund",
    "Total refunded shipping",
    "Total shipping price",
    "Total tax",
    "Total weight",
    "Unpaid",
    "Updated at"
  ],
  "Order / Line items": [
    "ID",
    "Name",
    "Discounted total",
    "Discounted unit price",
    "Fulfillable quantity",
    "Fulfillment service name",
    "Status",
    "Editable",
    "Non fulfillable quantity",
    "Total price",
    "Original unit price",
    "Product type",
    "Quantity",
    "Refundable quantity",
    "Requires Shipping",
    "Restockable",
    "SKU",
    "Taxable",
    "Title",
    "Total discount",
    "Unfulfilled discount total",
    "Unfulfilled original total",
    "Unfulfilled quantity",
    "Variant title",
    "Vendor"
  ]
};
